struct output{
    float4 position : POSITION;
    float2 texCoord : TEXCOORD;
};

output main(float2 position : POSITION, uniform float startX, uniform float endX, uniform float startY, uniform float endY)
{
    output OUT;
    OUT.position = float4(position, 0, 1);
    float w = endX - startX;
    float h = endY - startY;
    OUT.texCoord = float2(2.0 * (position.x - startX) / w - 1.0, 2.0 * (position.y - startY) / h - 1.0);
    return OUT;
}